### ISSUE TITLE
Error - can't use addon from main menu, anki 2.1.25+

### ISSUE THREAD

**Issue by An-png** [Arthur-Milchior/Anki-postpone-reviews#11]
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.26 (70784154) Python 3.8.1 Qt 5.14.1 PyQt 5.14.1
Platform: Linux
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-05-20 19:24:10
Add-ons possibly involved: ⁨Postpone cards review⁩

Caught exception:
Traceback (most recent call last):
  File "/home/superuser/.local/share/Anki2/addons21/1152543397/addToMain.py", line 17, in <lambda>
    addToMain(lambda: addDelay(getReviewCards()), _("Postpone cards"))
  File "/home/superuser/.local/share/Anki2/addons21/1152543397/addDay.py", line 31, in getReviewCards
    cids = finder.findCards("is:review")
TypeError: findCards() missing 1 required positional argument: 'order'

**Comment by An-png** [comment]
Just realised this bug was already reported on ankiweb by someone: 

> I also wasn't able to postpone all cards through the Tools >> Postpone with the newest 2.1.1.25+ update or whatever, but I was able to postpone decks individually which is fine

**Comment by rodrimix99** [comment]
doesn't work on 2.1.25

**Comment by Arthur-Milchior** [comment]
Please update the add-ons and try again. Close the issue if it's resolved

**Comment by An-png** [comment]
Yes, it works! Thank you!
